# pytorch_lightning==2.1.0
seed_everything: 123
trainer:
  accelerator: auto
  strategy: auto
  devices: [6]
  num_nodes: 1
  precision: null
  logger: null
  callbacks: null
  fast_dev_run: false
  max_epochs: -1
  min_epochs: null
  max_steps: 200000
  min_steps: null
  max_time: null
  limit_train_batches: null
  limit_val_batches: null
  limit_test_batches: null
  limit_predict_batches: null
  overfit_batches: 0.0
  val_check_interval: null
  check_val_every_n_epoch: 1
  num_sanity_val_steps: null
  log_every_n_steps: null
  enable_checkpointing: null
  enable_progress_bar: null
  enable_model_summary: null
  accumulate_grad_batches: 1
  gradient_clip_val: null
  gradient_clip_algorithm: null
  deterministic: null
  benchmark: null
  inference_mode: true
  use_distributed_sampler: true
  profiler: null
  detect_anomaly: false
  barebones: false
  plugins: null
  sync_batchnorm: false
  reload_dataloaders_every_n_epochs: 0
  default_root_dir: null
model:
  encoder: 
    class_path: SemiSupCon.models.encoders.samplecnn.SampleCNN
  temperature: 0.1
  optimizer:
    class_path: torch.optim.Adam
    init_args:
      lr: 0.0001
data:
  sl_task: 'mtat_top50'
  ssl_task: 'fma'
  target_length: 2.7
  target_sample_rate: 22050
  n_augmentations: 2
  transform: true
  n_classes: 50
  batch_size: 96
  num_workers: 32
  val_split: 0.1
  supervised_data_p: 0
  intrabatch_supervised_p: 0
  fully_supervised: false
  use_test_set: true
  aug_list:
  - 'gain'
  - 'polarity_inversion'
  - 'add_colored_noise'
  - 'filtering'
  # - 'pitch_shift'
  - 'delay'
  severity_modifier: 2
  sl_kwargs:
    csv_path : /import/c4dm-datasets/MagnaTagATune/annotations_final.csv
log: false
log_model: false
ckpt_path: Checkpoints
resume_id: null
resume_from_checkpoint: null